package org.omg.IOP;


/**
* org/omg/IOP/ENCODING_CDR_ENCAPS.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /System/Volumes/Data/jenkins/workspace/8-2-build-macosx-x64/jdk8u371/3355/corba/src/share/classes/org/omg/PortableInterceptor/IOP.idl
* Friday, March 17, 2023 3:56:47 AM GMT
*/

public interface ENCODING_CDR_ENCAPS
{

  /**
     * The CDR Encapsulation encoding.
     * @see CodecFactory
     */
  public static final short value = (short)(0);
}
