package com.sun.corba.se.spi.activation;


/**
* com/sun/corba/se/spi/activation/InitialNameService.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /Users/java_re/jenkins/workspace/8-2-build-macosx-x64-Xcode12.4-sans-NAS/jdk8u401/683/corba/src/share/classes/com/sun/corba/se/spi/activation/activation.idl
* Tuesday, December 19, 2023 6:12:33 PM GMT
*/

public interface InitialNameService extends InitialNameServiceOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface InitialNameService
