package org.omg.PortableServer;


/**
* org/omg/PortableServer/REQUEST_PROCESSING_POLICY_ID.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from /System/Volumes/Data/jenkins/workspace/8-2-build-macosx-aarch64-OS12.X-Xcode12.4-sans-NAS/jdk8u441/1521/corba/src/share/classes/org/omg/PortableServer/poa.idl
* Wednesday, December 4, 2024 8:04:25 AM GMT
*/

public interface REQUEST_PROCESSING_POLICY_ID
{

  /**
  	 * The value representing REQUEST_PROCESSING_POLICY_ID.
  	 */
  public static final int value = (int)(22L);
}
